# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    TWITTER_CONSUMER_KEY: '%env(TWITTER_CONSUMER_KEY)%'
    TWITTER_CONSUMER_SECRET: '%env(TWITTER_CONSUMER_SECRET)%'
    TWITTER_ACCESS_TOKEN: '%env(TWITTER_ACCESS_TOKEN)%'
    TWITTER_ACCESS_TOKEN_SECRET: '%env(TWITTER_ACCESS_TOKEN_SECRET)%'
    TWITTER_USER_ID: '%env(TWITTER_USER_ID)%'
    OPENSEA_API_KEY: '%env(OPENSEA_API_KEY)%'
    GOBLINIS_IMAGE_URL: '%env(GOBLINIS_IMAGE_URL)%'
    OPENSEA_ASSETS_URL: 'https://opensea.io/assets'
    GOBLINIS_IMAGE_FOLDER: 'goblinis-pictures'
    GOBLINIS_IMAGE_EXTENSION: 'png'
    GOBLINIS_CONTRACT_ADRESS: '0xe091f84499eeebda6f76638dca218541d63d8a67'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
